img_resize_sizes: [480, 640]

policy_io:
  action:
    topdown:
      horizon: 56
      normalization_type: ${NormalizationType:NONE}
      target_repr: null
      target_frequency: 5
      shift_right_by: 0.2
    joints_state_lowdim:
      horizon: 15
      normalization_type: ${NormalizationType:VARIANCE}
      target_repr: ${LieRepr:ABSOLUTE}
      target_frequency: 5
      shift_right_by: 0.2
  obs:
    topdown:
      horizon: 5
      normalization_type: ${NormalizationType:NONE}
      target_repr: null
      target_frequency: 5
      shift_right_by: 0
    joints_state_lowdim:
      horizon: 1
      normalization_type: ${NormalizationType:VARIANCE}
      target_repr: ${LieRepr:ABSOLUTE}
      target_frequency: 5
      shift_right_by: 0
    language_embedding:
      horizon: 1
      normalization_type: ${NormalizationType:NONE}
      target_repr: null
      target_frequency: null
      shift_right_by: 0


# concat_groups:
