_wandb:
    value:
        cli_version: 0.27.0
        e:
            verw5bqzksj4yajrra4mrumcqaf40pfu:
                args:
                    - --config=cosmos_predict2/configs/config.py
                    - --
                    - experiment=w2a_bi_yams_v2w_yams_unified_iter_000007000_fused_lr1.000e-04_layer20_bsz128
                    - trainer.max_iter=10000
                    - trainer.run_validation=True
                    - trainer.skip_initial_validation=True
                    - trainer.max_val_iter=8
                    - trainer.validation_iter=1000
                    - trainer.logging_iter=100
                    - trainer.grad_accum_iter=2
                    - checkpoint.save_iter=200
                    - optimizer=adamw
                    - dataloader_train.batch_size=1
                    - dataloader_train.num_workers=4
                    - dataloader_train.prefetch_factor=2
                    - optimizer.lr=1.0e-04
                    - model.config.pipe_config.net.atten_backend=flash_attn_no_cp
                    - world2action_pipe.net.atten_backend=flash_attn_no_cp
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "531415142400"
                        used: "431266549760"
                email: elias.andreoli@gmail.com
                executable: /home/ubuntu/mimic-video/model/.venv/bin/python3
                git:
                    commit: f2a38e30947ab149d52e6016a2165f869d8ad3c8
                    remote: git@github.com:ETHRoboticsClub/mimic-video.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Server Edition
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-4775eef5-d551-262d-0f42-7db0b1c4b170
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-df2f15f9-a363-7f6b-8f1e-292b876db53f
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-39ddb6e9-2af3-2e81-c55f-5a835c3aa51b
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-4113e5d5-12e1-a5a0-5d4e-e671034175fa
                host: ip-172-31-88-26
                memory:
                    total: "1073246048256"
                os: Linux-6.17.0-1013-aws-x86_64-with-glibc2.39
                program: -m scripts.train
                python: CPython 3.10.20
                root: /home/ubuntu/mimic-video/model
                startedAt: "2026-05-16T17:59:59.370645Z"
                writerId: verw5bqzksj4yajrra4mrumcqaf40pfu
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 71
                - 83
            "3":
                - 13
                - 15
                - 61
            "4": 3.10.20
            "5": 0.27.0
            "6": 4.51.3
            "10":
                - 20
            "12": 0.27.0
            "13": linux-x86_64
